# Generated by Django 2.0.6 on 2020-04-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200406_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('health_status', models.CharField(choices=[('Critical', 'Critical'), ('Risky', 'Risky'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=50)),
                ('next_checkup_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkuprecords',
            name='medicines',
            field=models.ManyToManyField(to='app.Medicine'),
        ),
        migrations.AddField(
            model_name='checkuprecords',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
