# Generated by Django 2.0.6 on 2020-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200407_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuprecords',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
