# Generated by Django 2.0.6 on 2020-04-07 11:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_num',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='luxuries',
            field=models.ManyToManyField(blank=True, null=True, to='app.Luxury'),
        ),
        migrations.AlterField(
            model_name='person',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
