# Generated by Django 2.0.6 on 2020-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200407_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='luxuries',
            field=models.ManyToManyField(to='app.Luxury'),
        ),
    ]
