# Generated by Django 2.0.6 on 2020-04-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200407_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
