# Generated by Django 2.0.6 on 2020-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200408_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
