# Generated by Django 2.0.6 on 2020-04-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200409_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='count',
        ),
    ]
