# Generated by Django 2.0.6 on 2020-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_person_doa'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
