# Generated by Django 2.0.6 on 2020-04-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_person_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_discharged', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discharged',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
