# Generated by Django 2.0.6 on 2020-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200418_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
