# Generated by Django 3.0.5 on 2020-04-03 22:17

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('family', 'A family with children less than 17 years of age'), ('adults', 'All adults above 18 years of age')], max_length=100)),
                ('facility_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('led_tv', 'LED TV'), ('free wifi', 'Free WiFi'), ('fridge', 'Refrigerator'), ('ac', 'Air Conditioner'), ('heater', 'Heater'), ('microwave', 'Microwave'), ('kettle', 'Kettle')], max_length=50)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('1', 'Ward 1'), ('2', 'Ward 2')], max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'Sleeper'), ('1', 'Economy'), ('2', 'Deluxe'), ('3', 'Super Deluxe')], max_length=50)),
                ('room_num', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('area', models.FloatField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('address', models.TextField()),
                ('contact_num', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('risk', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=50)),
                ('vip', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
                ('luxuries', models.ManyToManyField(to='app.Luxury')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room')),
            ],
        ),
    ]
