# Generated by Django 2.0.6 on 2020-04-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200404_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='luxuries',
            field=models.ManyToManyField(blank=True, to='app.Luxury'),
        ),
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
    ]
