# Generated by Django 2.0.6 on 2020-04-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200406_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
    ]
