# Generated by Django 2.0.6 on 2020-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200408_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='luxuries',
            field=models.ManyToManyField(blank=True, to='app.Luxury'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
