# Generated by Django 2.0.6 on 2020-04-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200408_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='room_count',
        ),
    ]
