# Generated by Django 2.0.6 on 2020-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='doa',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
