# Generated by Django 2.0.6 on 2020-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_facility_isvip'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
