# Generated by Django 2.0.6 on 2020-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_facility_isvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
